### ISSUE TITLE
Why Oomox need SDK version of runtime?

### ISSUE THREAD

**Issue by sabriunal** [flathub/com.github.themix_project.Oomox#14]
While exploring [Flathub statistics](https://flathub.org/statistics), I noticed that the majority of GNOME apps use `org.gnome.Platform`, while minority of apps use `org.gnome.Sdk`.

Do Oomox really need SDK version? 

https://github.com/flathub/com.github.themix_project.Oomox/blob/master/com.github.themix_project.Oomox.json#L3

For comparison

https://github.com/flathub/org.gnome.Calendar/blob/master/org.gnome.Calendar.json#L3-L5

Thanks.

**Comment by actionless** [comment]
does it still work if rebuilding with platform instead of sdk?

as far as i remember, either oomox gtk theme or gnome-colors icon theme needed some gdk or pixbuf executable which existed only in sdk

**Comment by sabriunal** [comment]
I'll test in a few days. I'm on a metered network now.

**Comment by actionless** [comment]
or mb `glib-compile-schemas`

**Comment by sabriunal** [comment]
It compiled but I have no idea how to test. Also not a big problem for users. So I close my issue. Thanks.

**Comment by actionless** [comment]
> but I have no idea how to test.

choose Theme Style "Oomox" and hit "Export Theme"
