### ISSUE TITLE
No such file or directory: 'xrdb': 'xrdb' when opening Oomox Colors file

### ISSUE THREAD

**Issue by Newbytee** [flathub/com.github.themix_project.Oomox#6]
Traceback: [oomox-flatpak.txt](https://github.com/flathub/com.github.themix_project.Oomox/files/4701700/oomox-flatpak.txt)
Oomox Colors file that reproduces it: [sharp-hyperdark2.zip](https://github.com/flathub/com.github.themix_project.Oomox/files/4701705/sharp-hyperdark2.zip)

This issue does not occur when using Oomox from this COPR: https://copr.fedorainfracloud.org/coprs/tcg/themes/

It is behind this Flatpak repo entry in terms of version, but seeing as this a file not found error I imagine the problem lies in the packaging.

**Comment by actionless** [comment]
that's because the theme file uses xrdb values:

```
ICONS_SYMBOLIC_PANEL=xrdb.color0
MENU_FG=xrdb.color7
SURUPLUS_GRADIENT2=xrdb.color4
```

you can fix it by manually editing the file to remove `xrdb.*` entries



the proper fix will come later by extracting xrdb-related functionality into a separate plugin (which won't be shipped with flatpak)

**Comment by actionless** [comment]
fixed in https://github.com/themix-project/oomox/commit/e1fa97946dad0aeb62e7927906ea4c97d1244800
