### ISSUE TITLE
Can't export GNOME Shell Theme (need to specify the version)

### ISSUE THREAD

**Issue by berkiyo** [flathub/com.github.themix_project.Oomox#7]
Hi there,

I've ran into an issue where if I try to export the GNOME Shell version of the Arc-style theme, it gives me this error.

![gnome-oomox-bug-flatpak](https://user-images.githubusercontent.com/38805550/94107351-a2dec980-fe80-11ea-91bb-a52953717cb9.png)

I've tried running it like so, `flatpak run com.github.themix_project.Oomox --with-gnome-shell=3.36`, but no luck. 

Any ideas?

**Comment by actionless** [comment]
@nana-4, do you have an idea how would be better to approach this case?

**Comment by nana-4** [comment]
In Materia, we specify [a default gnome-shell version as a fallback](https://github.com/nana-4/materia-theme/blob/master/src/gnome-shell/meson.build#L16). Arc could also have a similar solution, I guess?

Or Oomox could add a theme option for Arc-style to specify a gnome-shell version, I think.

But I'm not the maintainer of Arc, and maybe @jnsh has a better idea.

**Comment by jnsh** [comment]
I was under the impression that Arc-theme support was dropped from oomox, at least for the fork I'm maintaining. Looks like the build error is coming from building the obsolete arc-design/arc-theme repo.

Regardless, in Arc there's no fallback version. If the version can't be determined for cinnamon, gnome-shell or gtk3, the build will fail to avoid incorrect theme versions from getting installed, unbeknownst to the user. This should be the same for the arc-design project.

IIRC, oomox didn't support recoloring GNOME Shell? If this is correct, maybe you could just disable the building of gnome-shell theme altogether. Same goes for rest of the themes that oomox don't support.

**Comment by actionless** [comment]
@nana-4  oops, i thought it was about Materia

@jnsh , new people who pretend to maintain Arc-theme have broken all the stuff, so in the next release it will be removed anyway: https://github.com/themix-project/oomox/issues/293
